import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const EXPECTED_SNAPSHOT_SHA256 =
  "5ebbe33b73ffa20de28a11240bbd53660bb15f989a82fc48456358786a58b153";
const defaultSnapshotUrl = new URL(
  "../../docs/governance/contracts/openapi/frontend-mvp-backend-openapi.json",
  import.meta.url,
);
const defaultOutputUrl = new URL("../src/lib/api/openapi.generated.ts", import.meta.url);
const canonicalizeLineEndings = (value) => value.replace(/\r\n?/g, "\n");

function option(name) {
  const index = process.argv.indexOf(name);
  if (index === -1) return undefined;
  const value = process.argv[index + 1];
  if (!value || value.startsWith("--")) throw new Error(`${name} exige um caminho.`);
  return pathToFileURL(resolve(value));
}

const snapshotUrl = option("--snapshot") ?? defaultSnapshotUrl;
const outputUrl = option("--output") ?? defaultOutputUrl;

async function render() {
  const snapshot = await readFile(snapshotUrl);
  const snapshotHash = createHash("sha256").update(snapshot).digest("hex");
  if (snapshotHash !== EXPECTED_SNAPSHOT_SHA256) {
    throw new Error(
      `OpenAPI snapshot hash divergiu: ${snapshotHash} != ${EXPECTED_SNAPSHOT_SHA256}`,
    );
  }

  const ast = await openapiTS(snapshotUrl, {
    alphabetize: true,
    immutable: true,
  });
  const provenance = [
    "/**",
    " * This file was auto-generated by IMP-287. Do not edit manually.",
    " * Source: docs/governance/contracts/openapi/frontend-mvp-backend-openapi.json",
    ` * Snapshot SHA-256: ${snapshotHash}`,
    " */",
    "",
  ].join("\n");
  return `${provenance}${astToString(ast)}`;
}

async function main() {
  const mode = process.argv[2];
  if (mode !== "--write" && mode !== "--check") {
    throw new Error("Use --write ou --check.");
  }

  const expected = await render();
  if (mode === "--write") {
    await mkdir(new URL("../src/lib/api/", import.meta.url), { recursive: true });
    await writeFile(outputUrl, expected, "utf8");
    console.log(`OpenAPI types generated: ${fileURLToPath(outputUrl)}`);
    return;
  }

  let actual;
  try {
    actual = await readFile(outputUrl, "utf8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      throw new Error(`OpenAPI generated file ausente: ${fileURLToPath(outputUrl)}`);
    }
    throw error;
  }
  if (canonicalizeLineEndings(actual) !== expected) {
    throw new Error("OpenAPI generated types estao desatualizados; execute npm run api:generate.");
  }
  console.log("OpenAPI generated types match the governed snapshot in canonical LF form.");
}

await main();
